version: "3"
services:
  'php':
    restart: always
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    image: prozhou/php
    entrypoint: bash -c "/data/server/php/sbin/php-fpm && tail -f /etc/passwd"
    ports:
      - "9010:9010"
    depends_on:
      - "mysql"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
    environment:
      PATH: /data/server/php/bin:$PATH
  'nginx':
    restart: always
    image: prozhou/nginx
    entrypoint: bash -c "/data/server/nginx/sbin/nginx && tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    depends_on:
      - "php"
    ports:
      - "80:80"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
  'mysql':
    restart: always
    image: prozhou/mysql
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
        - {MYSQL_DATA}:/var/lib/mysql 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example

  'redis':
    restart: always
    image: prozhou/redis
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
  'go':
    restart: always
    image: prozhou/go
    entrypoint: bash -c "tour -http 0.0.0.0:3999"
    ports:
      - "3999:3999"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
    environment:
      PATH: /root/go/bin:$PATH
  'c':
    restart: always
    image: prozhou/cc
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
  'java':
    restart: always
    image: prozhou/java
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
