version: "3"
services:
  'php':
    restart: always
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    image: prozhou/php
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && /data/server/php/sbin/php-fpm && tail -f /etc/passwd
    
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - {WEBROOT}/wwwroot:/data/www/wwwroot
    environment:
      PATH: /data/server/php/bin:$PATH
  'go':
    restart: always
    image: prozhou/go
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && tail -f /etc/passwd
    depends_on:
      - "mysql"
      - "redis"
    ports:
      - "3999:3999"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}/go:/root/go
    environment:
      PATH: /root/go/bin:$PATH
      GOPATH: /root/go
  'java':
    restart: always
    image: prozhou/java
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && tail -f /etc/passwd
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}/wwwroot:/data/www/wwwroot
  'nginx':
    restart: always
    image: prozhou/nginx
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && /data/server/nginx/sbin/nginx && tail -f /etc/passwd
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    depends_on:
      - "php"
    ports:
      - "80:80"
    volumes:
      - {WEBROOT}/wwwroot:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
  'mysql':
    restart: always
    image: prozhou/mysql
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && if [ ! -d /usr/local/mysql/data/sys ];then rm -rf /usr/local/mysql/data/* && /usr/local/mysql/bin/mysqld --initialize-insecure --user=root;fi;/usr/local/mysql/bin/mysqld  --user=root;tail -f /etc/passwd
        
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
        - {MYSQL_DATA}:/usr/local/mysql/data
    ports:
      - "3306:3306"
  'redis':
    restart: always
    image: prozhou/redis
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && /data/server/redis/bin/redis-server;tail -f /etc/passwd
    ports:
      - "6397:6397"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
  'cpp':
    restart: always
    image: prozhou/cpp
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && tail -f /etc/passwd
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}/wwwroot:/data/www/wwwroot
  'python':
    restart: always
    image: prozhou/python
    entrypoint:
      - /bin/bash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && tail -f /etc/passwd
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}/wwwroot:/data/www/wwwroot
