version: "3"
services:
  'php':
    restart: always
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    image: prozhou/php
    entrypoint: bash -c "/data/server/php/sbin/php-fpm && tail -f /etc/passwd"
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
    environment:
      PATH: /data/server/php/bin:$PATH
  'go':
    restart: always
    image: prozhou/go
    entrypoint: bash -c "tail -f /etc/passwd"
    depends_on:
      - "mysql"
      - "redis"
    ports:
      - "3999:3999"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}/go:/root/go
    environment:
      PATH: /root/go/bin:$PATH
  'java':
    restart: always
    image: prozhou/java
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
  'nginx':
    restart: always
    image: prozhou/nginx
    entrypoint: bash -c "/data/server/nginx/sbin/nginx && tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    depends_on:
      - "php"
    ports:
      - "80:80"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
  'mysql':
    restart: always
    image: prozhou/mysql
    entrypoint: bash -c "if [ -d /usr/local/mysql/data/sys ];then /usr/local/mysql/bin/mysqld --initialize-insecure --user=root;fi;/usr/local/mysql/bin/mysqld  --user=root;tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
        - {MYSQL_DATA}:/usr/local/mysql/data
    ports:
      - "3306:3306"
  'redis':
    restart: always
    image: prozhou/redis
    entrypoint: bash -c "/data/server/redis/bin/redis-server;tail -f /etc/passwd"
    ports:
      - "6397:6397"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_SRV_CONF}:/data/server/nginx/conf/vhost/server.conf
      - {NGINX_MAIN_CONF}:/data/server/nginx/conf/nginx.conf
      - ./data/soft_etc/ssh:/root/.ssh
      - ./opt:/data/opt
  'cpp':
    restart: always
    image: prozhou/cpp
    entrypoint: bash -c "tail -f /etc/passwd"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - {WEBROOT}:/data/www/wwwroot
