version: "3"
services:
  'php':
    restart: always
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    image: lnmp 
    entrypoint: bash -c "/data/server/php/sbin/php-fpm && /root/go/bin/gotour -http '0.0.0.0:3999'"
    ports:
      - "9010:9010"
      - "3999:3999"
    depends_on:
      - "mysql"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
    environment:
      PATH: /data/server/php/bin:$PATH
  'nginx':
    restart: always
    image: lnmp 
    entrypoint: bash -c "/data/server/nginx/sbin/nginx && tail -f /etc/passwd"
    depends_on:
      - "php"
    ports:
      - "80:80"
    volumes:
      - {WEBROOT}:/data/www/wwwroot
      - {NGINX_CONF}:/data/server/nginx/conf/vhost/default.conf
  'mysql':
    restart: always
    image: mysql:8.0.12
    volumes:
        - {MYSQL_DATA}:/var/lib/mysql 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example


